-- 1. Create the brands table
CREATE TABLE public.brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    name TEXT UNIQUE NOT NULL,
    brand_logo TEXT
);

-- Enable Row Level Security (RLS) for the new table
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;

-- Grant permissions: Allow read for everyone, allow insert/update/delete for authenticated users
-- Adjust these permissions based on your app's specific needs (e.g., only admins can add brands)
CREATE POLICY "Enable read access for all users" ON public.brands FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.brands FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON public.brands FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Enable delete for authenticated users only" ON public.brands FOR DELETE TO authenticated USING (true);

-- Grant usage on the sequence to necessary roles if needed (usually handled by table grants)
GRANT USAGE ON SEQUENCE public.brands_id_seq TO authenticated;


-- 2. Populate the brands table with initial data
INSERT INTO public.brands (id, name, brand_logo) VALUES
(1, 'Jordan', 'https://cdn.sanity.io/images/pu5wtzfc/production/403ccf803ef3c2c8cd788c3102171c8d1caf2aed-37x37.svg'),
(6, 'Saucony', 'https://cdn.sanity.io/images/pu5wtzfc/production/49e76122c445694c80623bd47c32a8f479753c3c-37x37.svg'),
(2, 'Nike', 'https://cdn.sanity.io/images/pu5wtzfc/production/01f4f758f043a78a06af31a36d201fa982e6fb36-37x37.svg'),
(3, 'Adidas', 'https://cdn.sanity.io/images/pu5wtzfc/production/55b0c1b86632da8ee5adb25260e7d725d7d6aa29-37x37.svg'),
(5, 'New Balance', 'https://cdn.sanity.io/images/pu5wtzfc/production/a4ac3428f40301966847a679d76b30154bf78b99-37x37.svg'),
(4, 'Asics', 'https://cdn.sanity.io/images/pu5wtzfc/production/9440d6d7f09c5ad4cf8adba127c4305ceac70d35-37x37.svg'),
(7, 'Reebok', 'https://cdn.sanity.io/images/pu5wtzfc/production/03bb5444c409ee380b194774b2bbc08d6b7c4a4e-37x37.svg'),
(9, 'Other', 'https://cdn.sanity.io/images/pu5wtzfc/production/bdf04955c0e29c3df5763e11aadf277839c65c67-37x37.svg'),
(8, 'Puma', 'https://cdn.sanity.io/images/pu5wtzfc/production/9ceb99e3f4ffeaf9e2cd4286383bfca303c588a5-37x37.svg')
-- We need to manually set the sequence value after inserting specific IDs
-- Find the highest ID inserted (which is 9) and set the sequence to the next value (10)
ON CONFLICT (id) DO NOTHING; -- Avoid errors if IDs already exist somehow

SELECT setval('public.brands_id_seq', COALESCE((SELECT MAX(id) FROM public.brands), 1));


-- 3. Add brand_id column and foreign key to the items table
ALTER TABLE public.items
ADD COLUMN brand_id BIGINT;

ALTER TABLE public.items
ADD CONSTRAINT items_brand_id_fkey
FOREIGN KEY (brand_id) REFERENCES public.brands(id);

-- Optional: Add an index for faster lookups based on brand_id
CREATE INDEX idx_items_brand_id ON public.items(brand_id);

-- Note: We are NOT dropping the old 'brand' text column yet.
-- We'll do that after migrating the data in a later step.